dico_color = {
          'white':'white', 'green':'green','leopardprint':'other',
          'black':'black','yellow':'yellow', 'blue':'blue', 'navyblue':'blue',
          'grey':'grey','orange':'orange', 'red':'red','beige':'other',
          'lightblue':'blue','Black':'black','armygreen':'green',
          'khaki':'green', 'red & blue':'multicolor', 'blue & pink':'multicolor',
          'purple':'purple','RED':'red', 'white & green':'multicolor',
          'winered':'red', 'black & green':'multicolor','whitefloral':'white',
          'floral':'other', 'fluorescentgreen':'green', 'orange & camouflage':'orange',
          'lightyellow':'yellow', 'coolblack':'black','camouflage':'other','pink':'pink',
          'lightpink':'pink', 'pink & black':'multicolor', 'silver':'other',
          'Army green':'green', 'lightgreen':'green','mintgreen':'green',
          'pink & grey':'multicolor', 'gray':'grey', 'coffee':'other', 'rose':'red',
          'light green':'green', 'leopard':'other', 'black & white':'multicolor',
          'orange-red':'red','dustypink':'pink', 'White':'white', 'star':'other',
          'white & black':'multicolor', 'apricot':'orange','skyblue':'blue',
          'burgundy':'red', 'claret':'purple', 'pink & white':'multicolor',
          'rosered':'red', 'tan':'other','navy blue':'blue', 'wine red':'red',
          'lightred':'red', 'Pink':'pink', 'coralred':'red', 'brown':'other',
          'lakeblue':'blue', 'darkblue':'blue', 'camel':'other', 'pink & blue':'multicolor',
          'nude':'other', 'Blue':'blue','lightpurple':'purple', 'army':'other',
          'black & stripe':'multicolor', 'Rose red':'red','greysnakeskinprint':'other',
          'denimblue':'blue', 'applegreen':'green', 'offwhite':'white','lightgray':'grey',
          'navy':'blue', 'gray & white':'multicolor', 'brown & yellow':'multicolor',
          'winered & yellow':'multicolor', 'army green':'green', 'whitestripe':'white',
          'rainbow':'other','lightgrey':'grey', 'watermelonred':'green',
          'prussianblue':'blue', 'navyblue & white':'multicolor','white & red':'multicolor',
          'wine':'red', 'ivory':'white', 'black & yellow':'multicolor', 'jasper':'other',
          'lightkhaki':'green', 'offblack':'black', 'violet':'purple',
          'black & blue':'multicolor', 'blackwhite':'other','darkgreen':'green', 'rosegold':'pink',0:'other'
}

dico_size= {
         'M':'M', 'XS':'XS', 'S':'S', 'Size-XS':'XS', 'M.':'M',
         'XXS':'XXS', 'L':'L', 'XXL':'XXL','S.':'S',
         's':'S','choose a size':'other', 'XS.':'XS', '32/L':'L',
         'Suit-S':'S', 'XXXXXL':'other', 'EU 35':'S',
         '4':'other','Size S.':'S', '1m by 3m':'other', '3XL':'other',
         'Size S':'S', 'XL':'XL', 'Women Size 36':'S',
         'US 6.5 (EU 37)':'M', 'XXXS':'other', 'SIZE XS':'XS',
         '26(Waist 72cm 28inch)':'M','Size XXS':'XXS',
         '29':'other', '1pc':'other', '100 cm':'other',
         'One Size':'other', 'SIZE-4XL':'other', '1':'other',
         'S/M(child)':'other', '2pcs':'other', 'XXXL':'other',
         'S..':'S', '30 cm':'L', '5XL':'other', '33':'S',
         'Size M':'M', '100 x 100cm(39.3 x 39.3inch)':'other',
         '100pcs':'other', '2XL':'XXL', '4XL':'other',
         'SizeL':'L', 'SIZE XXS':'XXL', 'XXXXL':'other',
         'Base & Top & Matte Top Coat':'other','size S':'S',
         '35':'S', '34':'S', 'SIZE-XXS':'XXS', 'S(bust 88cm)':'S',
         'S (waist58-62cm)':'S', 'S(Pink & Black)':'S', '20pcs':'other', 'US-S':'S',
         'Size -XXS':'XXS', 'X   L':'XL', 'White':'other',
         '25':'other', 'Size-S':'S', 'Round':'other',
         'Pack of 1':'other', '1 pc.':'other', 'S Diameter 30cm':'S', '6XL':'other',
         'AU plug Low quality':'other', '5PAIRS':'other',
         '25-S':'S', 'Size/S':'S', 'S Pink':'S',
         'Size-5XL':'other', 'daughter 24M':'other', '2':'other',
         'Baby Float Boat':'other', '10 ml':'other', '60':'other',
         'Size-L':'L', 'US5.5-EU35':'S', '10pcs':'other',
         '17':'other', 'Size-XXS':'XXS', 'Women Size 37':'M',
         '3 layered anklet':'other', '4-5 Years':'other',
         'Size4XL':'other', 'first  generation':'other',
         '80 X 200 CM':'other', 'EU39(US8)':'L', 'L.':'L',
         'Base Coat':'other', '36':'M', '04-3XL':'other',
         'pants-S':'S', 'Floating Chair for Kid':'other',
         '20PCS-10PAIRS':'other', 'B':'other',
         'Size--S':'S', '5':'other', '1 PC - XL':'XL',
         'H01':'other', '40 cm':'other', 'SIZE S':'S'
}